### ISSUE TITLE
getCrc() fails sometimes

### ISSUE THREAD

**Issue by wapmorgan** [Gemorroj/Archive7z#30]
For few archive types, CRC is not parsed from `7z l`, so it is empty, so it fails with Exception
```
Fatal error: Uncaught TypeError: Archive7z\Entry::getCrc(): Return value must be of type string, null returned in /app/vendor/gemorroj/archive7z/src/Entry.php:240
Stack trace:
#0 /app/src/Drivers/SevenZip.php(217): Archive7z\Entry->getCrc()
#1 /app/src/UnifiedArchive.php(284): wapmorgan\UnifiedArchive\Drivers\SevenZip->getFileData('doc')
#2 /app/src/Commands/TableCommand.php(66): wapmorgan\UnifiedArchive\UnifiedArchive->getFileData('doc')
```

I found that crc is present for ZIP/TAR.GZ, and not present for TAR

**Comment by wapmorgan** [comment]
And for ISO files there's another problem: `Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /app/vendor/gemorroj/archive7z/src/Entry.php on line 189`.
Output of `/usr/bin/7z` command [7zl.txt](https://github.com/Gemorroj/Archive7z/files/9042217/7zl.txt) attached

**Comment by wapmorgan** [comment]
And even empty Path:
```
TypeError: Archive7z\Entry::getPath(): Return value must be of type string, null returned

/app/vendor/gemorroj/archive7z/src/Entry.php:278
/app/vendor/gemorroj/archive7z/src/Entry.php:283
/app/src/Drivers/SevenZip.php:171
/app/tests/DriversTest.php:110
```
for listing file https://github.com/wapmorgan/UnifiedArchive/releases/download/0.0.1/onefile.xz

**Comment by Gemorroj** [comment]
@wapmorgan tnx. i have fixed some problems except empty path in xz archive. i will think about how to fix it.
